login/urls.py
from django.urls import path, include 
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('', auth_views.LoginView.as_view(template_name="login.html"), name='login'),
]

reread/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import *
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',HomePageView,name='home'),
    path('user/', include('user.urls')),
    path('signup/', include('signup.urls')),
    path('login/', include('login.urls')),
]

signup/urls.py
from django.urls import path
from signup import views

urlpatterns = [
    path('', views.signup, name='signup'),
]

user/urls.py
from django.urls import path, include 
from .views import *

urlpatterns = [
    path('', userHomePage, name='user_home'),
    path('delete_file/',deleteFile, name="delete_file"),
    path('upload/',fileUploadView,name='upload'),
    path('keywords/', keywordView, name='keyword'),
    path('display_summary/',displaySummaryView, name="display_summary_view"),
    path('grammar_check/',grammarCheckerView, name="grammar_checker_view"),
    path('download/',downloadView, name='download'),
    path('logout/',logout_page, name='logout'),
]

login/models.py
from django.db import models

# Create your models here.

signup/models.py
from django.db import models

# Create your models here.

signup/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )

user/forms.py
from django import forms
from user.models import Document

class UploadFileForm(forms.Form):
    title = forms.CharField(max_length=50)
    file = forms.FileField()

login/views.py
from django.shortcuts import render

# Create your views here.

signup/views.py
from django.contrib.auth import login, authenticate
from django.shortcuts import render, redirect
from .forms import SignUpForm

def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('user_home')
    else:
        form = SignUpForm()
    return render(request, 'signup.html', {'form': form})

templates/display_uploaded_file.html
<html>
	<head>
		<title>File contents</title>
		<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
	</head>
	<body>
		<p>
			<h3>Contents of the file - </h3><br>
			{{ content }}
		</p>
	</body>
</html>

templates/extender.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <link rel="icon" type="image/png" href="/static/dashboard/img/favicon.ico">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

    <title>Dashboard</title>

    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />


    <!-- Bootstrap core CSS     -->
    <link href="/static/dashboard/css/bootstrap.min.css" rel="stylesheet" />

    <!-- Animation library for notifications   -->
    <link href="/static/dashboard/css/animate.min.css" rel="stylesheet"/>

    <!--  Light Bootstrap Table core CSS    -->
    <link href="/static/dashboard/css/light-bootstrap-dashboard.css?v=1.4.0" rel="stylesheet"/>


    <!--  CSS for Demo Purpose, don't include it in your project     -->
    <link href="/static/dashboard/css/demo.css" rel="stylesheet" />


    <!--     Fonts and icons     -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Roboto:400,700,300' rel='stylesheet' type='text/css'>
    <link href="/static/dashboard/css/pe-icon-7-stroke.css" rel="stylesheet" />

</head>
<body>

<div class="wrapper">
    <div class="sidebar">

    <!--

        Tip 1: you can change the color of the sidebar using: data-color="blue | azure | green | orange | red | purple"
        Tip 2: you can also add an image using data-image tag

    -->

        <div class="sidebar-wrapper" style="background: #0177A7;">
            <div class="logo">
                <a href="#" class="simple-text">
                    Welcome, {{ username }}
                </a>
            </div>

            <ul class="nav">
                <li>
                    <a href="/user/">
                        <i class="pe-7s-home"></i>
                        <p>Home</p>
                    </a>
                </li>
                <li>
                    <a href="/user/upload">
                        <i class="pe-7s-upload"></i>
                        <p>Upload a file</p>
                    </a>
                </li>
                <li>
                    <a href="/user/display_summary">
                        <i class="pe-7s-filter"></i>
                        <p>Summarisation</p>
                    </a>
                </li>
                <li>
                    <a href="/user/keywords">
                        <i class="pe-7s-key"></i>
                        <p>Keyword Extraction</p>
                    </a>
                </li>
                <li>
                    <a href="/user/grammar_check">
                        <i class="pe-7s-search"></i>
                        <p>Grammarnazi</p>
                    </a>
                </li>
            </ul>
        </div>
    </div>

    <div class="main-panel">
        <nav class="navbar navbar-inverse navbar-fixed">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation-example-2">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="/">ReRead</a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav navbar-right">
                        <li>
                            <a href="/user/logout">
                                <p>Log out</p>
                            </a>
                        </li>
                        <li class="separator hidden-lg"></li>
                    </ul>
                </div>
            </div>
        </nav>
            <div class="content" style="background-image: url('/static/dashboard/img/bg4.jpg'); background-size: cover;background-repeat: no-repeat;background-position: center center;">
                <div class="container-fluid">
                    {% block content %}
                    <div class="row">
                        <div class="col-md-3">
                            <div class="card" style="background:#222;color:white;">
                                <div class="header">
                                    <h4>Your Files</h4>
                                </div>
                                <div class="content">
                                    <div class="table-full-width" style = "overflow-y:scroll;height:300px;display:block;" id="file_names">
                                        <table class="table">
                                            <tbody>
                                                {% for file in files %}
                                                <tr>
                                                   <!--  <td>
                                                        <div class="checkbox">
                                                            <input id="checkbox1" type="checkbox">
                                                            <label for="checkbox1"></label>
                                                        </div>
                                                    </td> -->
                                                    <td style="text-align: center;"><button type="button" id="file_button_{{ forloop.counter }}" class="btn btn-default" data-toggle="modal" data-target="#myModal" value="{{ file }}">{{ file }}</button></td>
                                                    <!-- <td class="td-actions text-right">
                                                        <button type="button" rel="tooltip" title="Edit Task" class="btn btn-info btn-simple btn-xs">
                                                            <i class="fa fa-edit"></i>
                                                        </button>
                                                        <button type="button" rel="tooltip" title="Remove" class="btn btn-danger btn-simple btn-xs">
                                                            <i class="fa fa-times"></i>
                                                        </button>
                                                    </td> -->
                                                </tr>
                                                {% endfor %}
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endblock %}
                </div>
            </div>
    

        <footer class="footer" style="background: #222; border: none; padding: 1px">
                <h4 style="text-align: center; color: white;">
                    &copy; <script>document.write(new Date().getFullYear())</script> ReRead, made with love for better research.
                </p>
        </footer>

    </div>
</div>

<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog" style="width: auto; max-width: 900px;">

    <!-- Modal content-->
    <div class="modal-content"style="background:#222;color:white;">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title" style="text-align: center;">File Content</h4>
      </div>
      <div class="modal-body">
        <p id="myModalBody"></p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal" id="modal_close_button">Close</button>
      </div>
    </div>

  </div>
</div>


</body>

    <!--   Core JS Files   -->
    <script src="/static/dashboard/js/jquery.3.2.1.min.js" type="text/javascript"></script>
    <script src="/static/dashboard/js/bootstrap.min.js" type="text/javascript"></script>

    <!--  Charts Plugin -->
    <script src="/static/dashboard/js/chartist.min.js"></script>

    <!--  Notifications Plugin    -->
    <script src="/static/dashboard/js/bootstrap-notify.js"></script>

    <!--  Google Maps Plugin    -->
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>

    <!-- Light Bootstrap Table Core javascript and methods for Demo purpose -->
    <script src="/static/dashboard/js/light-bootstrap-dashboard.js?v=1.4.0"></script>

    <!-- Light Bootstrap Table DEMO methods, don't include it in your project! -->
    <script src="/static/dashboard/js/demo.js"></script>

    <script src="/static/dashboard/js/jquery.cookie.js"></script>

    {% csrf_token %}
    <script type="text/javascript">
        var csrftoken = $.cookie('csrftoken');

        $(document).ready(function(){

            demo.initChartist();

            $.notify({
                icon: 'pe-7s-study',
                message: "Welcome to the <b>ReRead Dashboard</b> - Let's refine those documents!"

            },{
                type: 'info',
                timer: 4000
            });

        });

        function csrfSafeMethod(method) {
            // these HTTP methods do not require CSRF protection
            return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
        }

        $.ajaxSetup({
            beforeSend: function(xhr, settings) {
                if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                    xhr.setRequestHeader("X-CSRFToken", csrftoken);
                }
            }
        });

        $("[id^=file_button]").click(function(e){
            console.log('click button')
            e.preventDefault();
            $.ajax({
                type: "POST",
                url : "{% url 'user_home' %}",
                data: { 'name' : $(this).val() },
                success: function(result){
                    console.log(result)
                    if(result.file_content){
                        document.getElementById("myModalBody").innerHTML = result.file_content;                        
                    }
                    else{
                        document.getElementById("myModalBody").innerHTML = "<i>File is empty</i>";
                    }
                }
            })
        })

        $("#myModal").on('hidden.bs.modal', function(){
            console.log('close modal')
            document.getElementById("myModalBody").innerHTML = "";
        })


    </script>

</html>

templates/grammar.html
{% extends 'extender.html' %}                         
{% block content %}
<title>Correct Grammar</title>
<div class="row">
	<div class="col-md-2"></div>
	<div class="col-md-8">
		<div class="card" style="background: #222; color: white">
		    <div class="header">
		        <h4 class="title" style="color: white;text-align: center;">Choose a File to Process</h4>
		    </div>
		    <div class="content">
		        <div class="table-full-width" style = "overflow-y:scroll;height:auto;max-height: 700px;display:block;" id="file_names">
		            <table class="table">
		                <tbody>
		                	<tr>
		                		<th style="text-align: center;">File Name</th>
		                		<th>   </th>
		                	</tr>
		                	{% if files|length < 1 %}
                                                <tr><td><i>No files uploaded</i></td></tr>
                                                {% endif %}
		                    {% for file in files %}
		                    <tr>
		                        <input style="display: none;" value="{{ file }}" name="filename"><td style="text-align: center;"><button type="button" id="file_button_{{ forloop.counter }}" class="btn btn-default" data-toggle="modal" data-target="#myModal" value="{{ file }}" name="filename">{{ file }}</button></td>
		                        <td><a href="/user/grammar_check?filename={{ file }}"><button class="btn btn-info" type="submit">Correct It!</button></a></td>
		                    </tr>
		                    {% endfor %}
		                </tbody>
		            </table>
		        </div>
		    </div>
		</div>
	</div>
	<div class="col-md-2"></div>
</div>
{% endblock %}

templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>ReRead</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'homepage/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="{% static 'homepage/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>

    <!-- Plugin CSS -->
    <link href="{% static 'homepage/vendor/magnific-popup/magnific-popup.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/static/homepage/css/creative.min.css" rel="stylesheet">

  </head>

  <body id="page-top">

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
      <div class="container">
        <a class="navbar-brand js-scroll-trigger" href="#page-top">ReRead Research Tool</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="#about">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="#services">Services</a>
            </li>
            {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link js-scroll-trigger" href="{% url 'user_home' %}">Dashboard</a>
              </li>
              <li class="nav-item">
                <a class="nav-link js-scroll-trigger" href="{% url 'logout' %}">Logout</a>
              </li>
            {% else %}
              <li class="nav-item">
                <a class="nav-link js-scroll-trigger" href="{% url 'login' %}">Login</a>
              </li>
              <li class="nav-item">
                <a class="nav-link js-scroll-trigger" href="{% url 'signup' %}">Sign Up</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>

    <header class="masthead text-center text-white d-flex">
      <div class="container my-auto">
        <div class="row">
          <div class="col-lg-10 mx-auto">
            <h1 class="text-uppercase">
              <strong>Improve the way you do your research, today!</strong>
            </h1>
            <hr>
          </div>
          <div class="col-lg-8 mx-auto">
            <a class="btn btn-primary btn-xl js-scroll-trigger" href="#about">Find Out More</a>
          </div>
        </div>
      </div>
    </header>

    <section class="bg-primary" id="about">
      <div class="container">
        <div class="row">
          <div class="col-lg-8 mx-auto text-center">
            <h2 class="section-heading text-white">We've got what you need!</h2>
            <hr class="light my-4">
            <p class="text-faded mb-4">We help you not only discover more content, but also refine and improve the content that you already have. With the technicalities, you remain the boss, but we help you with the small things that matter, and can turn your document from a good one to a great one!</p>
            <a class="btn btn-light btn-xl js-scroll-trigger" href="#services">Get Started!</a>
          </div>
        </div>
      </div>
    </section>

    <section id="services">
      <div class="container">
        <div class="row">
          <div class="col-lg-12 text-center">
            <h2 class="section-heading">At Your Service</h2>
            <hr class="my-4">
          </div>
        </div>
      </div>
      <div class="container">
        <div class="row">
          <div class="col-lg-3 col-md-6 text-center">
            <div class="service-box mt-5 mx-auto">
              <i class="fas fa-4x fa-exclamation-triangle text-primary mb-3 sr-icon-1"></i>
              <h3 class="mb-3">Grammatical Error Detection</h3>
              <p class="text-muted mb-0">Iron out the grammatical mistakes from your document.</p>
            </div>
          </div>
          <div class="col-lg-3 col-md-6 text-center">
            <div class="service-box mt-5 mx-auto">
              <i class="fas fa-4x fa-file-archive text-primary mb-3 sr-icon-2"></i>
              <h3 class="mb-3">Abstract Summarisation</h3>
              <p class="text-muted mb-0">Give us the crux, and we'll prepare an abstract as per your specifications.</p>
            </div>
          </div>
          <div class="col-lg-3 col-md-6 text-center">
            <div class="service-box mt-5 mx-auto">
              <i class="fas fa-4x fa-search text-primary mb-3 sr-icon-3"></i>
              <h3 class="mb-3">Keyword Extraction</h3>
              <p class="text-muted mb-0">Find out what would be the best way to give your document a theme.</p>
            </div>
          </div>
          <div class="col-lg-3 col-md-6 text-center">
            <div class="service-box mt-5 mx-auto">
              <i class="fas fa-4x fa-book text-primary mb-3 sr-icon-4"></i>
              <h3 class="mb-3">Literature Survey</h3>
              <p class="text-muted mb-0">We'll help you get more info on the go!</p>
            </div>
          </div>
        </div>
      </div>
    </section>

    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'homepage/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'homepage/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Plugin JavaScript -->
    <script src="{% static 'homepage/vendor/jquery-easing/jquery.easing.min.js' %}"></script>
    <script src="{% static 'homepage/vendor/scrollreveal/scrollreveal.min.js' %}"></script>
    <script src="{% static 'homepage/vendor/magnific-popup/jquery.magnific-popup.min.js' %}"></script>

    <!-- Custom scripts for this template -->
    <script src="{% static 'homepage/js/creative.min.js' %}"></script>

  </body>

</html>

templates/keyword_extraction.html
{% extends 'extender.html' %}                         
{% block content %}
<title>Keyword Extraction</title>
{% if content|length > 0 %}
<div class="col-md-6" style="align-self: center;">
	<div class="card" style="background: #222; color: white;">
		<div class="header">
			<h4 class="title" style="color: white;">Keywords and References</h4>
		</div>
		<div class="content">
			<div class="table-full-width" style="overflow-y: scroll;height: 300px;display: block;" id="links">
				<table class="table" style="text-align: center;">
					<thead style="text-align: center;">
						<tr>
							<th>Keyword</th>
							<th>Links</th>
						</tr>
					</thead>
					<tbody>
						{% for key,value in content.items %}
						<tr>
							<td rowspan="{{ value|length|add:1 }}"><h5><b>{{ key }}</b></h5></td>
							<td>
								{% for link in value %}
									<tr>
										<td><a href="{{ link }}">Link {{ forloop.counter }}</a></td>
									</tr>
								{% endfor %}
							</td>
						</tr>
						{% endfor %}
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>
{% endif %}
{% if papers|length > 0 %}
<div class="col-md-6" style="align-self: center;">
	<div class="card" style="background: #222; color: white;">
		<div class="header">
			<h4 class="title" style="color: white;">Relevant Papers</h4>
		</div>
		<div class="content">
			<div class="table-full-width" style="overflow-y: scroll;height: 300px;display: block;" id="links">
				<div class="content table-responsive table-full-width">
				<table class="table table-hover" style="text-align: center;">
					<thead style="text-align: center;">
						<tr>
							<th>Paper Title</th>
						</tr>
					</thead>
					<tbody>
						{% for key,value in papers.items %}
						<tr>
							<td><a href="{{ value }}">{{ key }}</a></td>
						</tr>
						{% endfor %}
					</tbody>
				</table>
			</div>
			</div>
		</div>
	</div>
</div>
{% endif %}
<div class="row">
	<div class="col-md-2"></div>
	<div class="col-md-8">
		<div class="card" style="background: #222; color: white;">
		    <div class="header">
		        <h4 class="title" style="color: white;text-align: center;">Choose a File to Extract Keywords</h4>
		    </div>
		    <div class="content">
		        <div class="table-full-width" style = "overflow-y:scroll;height:auto;max-height: 700px;;display:block;" id="file_names">
		            <table class="table">
		                <tbody>
		                	<tr>
		                		<th style="text-align: center;">File Name</th>
		                		<th>    </th>
		                	</tr>
		                	{% if files|length < 1 %}
                                                <tr><td><i>No files uploaded</i></td></tr>
                                                {% endif %}
		                    {% for file in files %}
		                    <tr>
		                        <input style="display: none;" value="{{ file }}" name="filename"><td style="text-align: center;"><button type="button" id="file_button_{{ forloop.counter }}" class="btn btn-default" data-toggle="modal" data-target="#myModal" value="{{ file }}" name="filename">{{ file }}</button></td>
		                        <td><a href = "/user/keywords?filename={{ file }}"><button class="btn btn-info" type="submit">Extract</button></a></td>
		                    </tr>
		                    {% endfor %}
		                </tbody>
		            </table>
		        </div>
		    </div>
		</div>
	</div>
	<div class="col-md-2"></div>
</div>
{% endblock %}

templates/summary.html
{% extends 'extender.html' %}                         
{% block content %}
<title>Create Summary</title>
<div class="row">
	<div class="col-md-2"></div>
	<div class="col-md-8">
		<div class="card" style="background: #222; color: white;">
		    <div class="header">
		        <h4 class="title" style="color: white;text-align: center;">Choose a File to Process</h4>
		    </div>
		    <div class="content">
		        <div class="table-full-width" style = "overflow-y:scroll;height:auto;max-height: 700px;display:block;" id="file_names">
		            <table class="table">
		                <tbody>
		                	<tr>
		                		<th style="text-align: center;">File Name</th>
		                		<th>Shrink To (Percentage of Original)</th>
		                		<th>   </th>
		                	</tr>
		                	{% if files|length < 1 %}
                                                <tr><td><i>No files uploaded</i></td></tr>
                                                {% endif %}
		                    {% for file in files %}
		                    <tr>
		                        <input style="display: none;" value="{{ file }}" name="filename"><td style="text-align: center;"><button type="button" id="file_button_{{ forloop.counter }}" class="btn btn-default" data-toggle="modal" data-target="#myModal" value="{{ file  }}" name="filename">{{ file }}</button></td>
		                        <td><input style="color:black;" id='pct_{{ file }}' name="percentage" placeholder="Enter Percentage (1-100)"></td>
		                        <td><a href='' onclick="this.href='/user/display_summary?filename={{ file }}&pct='+document.getElementById('pct_{{ file }}').value"><button class="btn btn-info" type="submit">Process</button></a></td>
		                    </tr>
		                    {% endfor %}
		                </tbody>
		            </table>
		        </div>
		    </div>
		</div>
	</div>
	<div class="col-md-2"></div>
</div>
{% endblock %}

templates/upload.html
{% extends 'extender.html' %}                         
{% block content %}
<title>Upload File</title>
<div class = "card" style="position: absolute; top: 30%; left: 35%;  align-content: right;text-align: center; padding: 50px; background: #1DC7EA;">
	<form name = "mainForm" method="post" enctype="multipart/form-data" style="display: inline-block;">
		{% csrf_token %}	
		<p><label for="id_title" style="color:white;">Title:</label> <input type="text" name="title" maxlength="50" required id="id_title"></p>
		<p><label for="id_file" style="color: white;">File:</label> <input type="file" accept=".txt" name="file" required id="id_file" onchange="checkExt();"></p>
		<button type="submit" style="color: black;">Upload</button>
	</form>
</div>
<script type="text/javascript">
	function checkExt() {
		if(document.mainForm.file.value.lastIndexOf(".txt") == -1){
			alert('Please upload a .txt file');
			document.getElementById('id_title').value = '';
			return;
		}
	}
</script>
{% endblock %}